apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "jx-bdd.name" . }}-{{ .Release.Namespace }}
{{ if .Values.clusterrole.rules -}}
rules:
{{ toYaml .Values.clusterrole.rules | indent 0 }}
{{- end }}