apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "jx-bdd.name" . }}
rules:
- apiGroups: [""]
  resources:
  - configmaps
  - pods
  - pods/log
  verbs: ["get", "list", "watch"]
- apiGroups:
  - jenkins.io
  - preview.jenkins.io
  resources: ["*"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["tekton.dev"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
