apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name:  {{ template "jx-bdd.name" . }}
subjects:
  - kind: ServiceAccount
    name: "{{ .Values.serviceAccount.name | default "jx-bdd" }}"
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name:  {{ template "jx-bdd.name" . }}
  apiGroup: rbac.authorization.k8s.io
