bdd:
  # the git secret name used to find the git user and token
  gitSecret: tekton-git

  # the git organisation used to create quickstarts inside. Defaults to the git user
  owner: ""

  # the git server host
  gitServerHost: "github.com"

  # the name of the quickstart to test
  quickstart: golang

command:
  - bash
  - -c 

args:
  - |
    git clone https://github.com/jenkins-x/bdd-jx3
    cd bdd-jx3
    jx gitops git setup
    go mod download
    make test-quickstart-golang-http

image:
  repository: gcr.io/jenkinsxio/jx-bdd
  tag: 1.0.12
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: "jx-bdd"
  # a map of annotations to add to the ServiceAccount
  annotations: {}

# define environment variables here as a map of key: value
env: {}

# a map of annotations to add to the pod
podAnnotations: {}

jobAnnotations: {}

resources:
  limits:
    cpu: 4
    memory: 6144Mi
  requests:
    cpu: 1
    memory: 2048Mi

nodeSelector: {}

tolerations: []

affinity: {}

terminationGracePeriodSeconds: 30

activeDeadlineSeconds: 12000

backoffLimit: 0

# default is Always but for Jobs use Never or OnFailure
restartPolicy: Never

clusterrole:
  rules:
  - apiGroups:
    - ""
    resources:
    - pods
    - pods/log
    - secrets
    - services
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ""
    resources:
    - namespaces
    verbs:
    - get
    - list
  - apiGroups:
    - tekton.dev
    resources:
    - pipelines
    - pipelineruns
    - tasks
    - taskruns
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - apps
    resources:
    - deployments
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - extensions
    - "networking.k8s.io" # k8s 1.14+
    resources:
    - ingresses
    verbs:
    - get
    - list
    - watch
